### ISSUE TITLE
No longer needed, might want to make that clear in the README

### ISSUE THREAD

**Issue by webmaven** [jonparrott/Darth-Vendor#7]

**Comment by j-walker23** [comment]
@webmaven I just came across this for the first time. Seems handy. 

Why do you say it is no longer needed? Did app engine do something cool? If so i can't find anything in their release notes

**Comment by jonparrott** [comment]
It's [part of the SDK](https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/ext/vendor/__init__.py), so you can do:

```
from google.appengine.ext import vendor

vendor.add('lib')
```

**Comment by j-walker23** [comment]
Oh ok. Thank you for clarifying, the pip install part of this is still valid though right?
