### ISSUE TITLE
Only one vendor call? 

### ISSUE THREAD

**Issue by j-walker23** [jonparrott/Darth-Vendor#8]
Thanks for this!!

I am wondering if i can use this to set other "lib" type folders on the system path.

Really meaning can i do this
`vendor.add('libs')`
`vendor.add('src/main/python')`

**Comment by jonparrott** [comment]
tbh, I don't know. I don't see why it wouldn't work. Try it and see?

Also, note that this is now in the appengine SDK under ``google.appengine.ext.vendor``, so you don't need to manually add it to your project.

**Comment by j-walker23** [comment]
That is the funny thing. The appengine vendor call did not work when i added a second directory the other day.

But yours did! Does that make sense, meaning are you doing anything different. Or did i just mess something up when i thought it wasn't working lol.

**Comment by jonparrott** [comment]
They should be identical, but I can verify.

**Comment by j-walker23** [comment]
Hmm, weird. It is for sure possible that i had something else broken at the time and just thought it was the multiple vendor calls.
